version: "2.1"
services:
    redis:
        hostname: redis
        image: redis
        ports:
            - "6379:6379" 
        restart: always
    
    mysql:
      image: mysql
      container_name: mysql
      hostname: mysql
      command: --default-authentication-plugin=mysql_native_password --mysqlx=0
      ports:
        - 3308:3306
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=cart
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
      healthcheck:
        test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 30s
        retries: 5
      restart: always

    django:
        container_name: web
        build: 
          context: ../
          dockerfile: Dockerfile
        volumes:
          - "../:/usr/src/app"
        depends_on:
          mysql:
            condition: service_healthy
        command: bash -c "python manage.py makemigrations && python manage.py migrate && supervisord -n"
        ports:
            - "8700:8700"
            - "5001:5001"
        sysctls:
            - net.core.somaxconn=65535

    nginx:
      image: nginx:1.19.5-alpine
      depends_on:
        - django
      ports:
        - "80:80" 
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
        - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
        - ../static/:/static/
      restart: always