version: "3"
services:
    redis:
        hostname: redis
        image: redis
        ports:
            - "6379:6379" 
        restart: always
    
    mysql:
      image: mysql
      container_name: mysql
      hostname: mysql
      command: --default-authentication-plugin=mysql_native_password --mysqlx=0
      ports:
        - 3308:3306
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=cart
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
      restart: always

    django:
        container_name: web
        build: 
          context: ../
          dockerfile: Dockerfile
        volumes:
          - "../:/usr/src/app"

        command: supervisord -n
        ports:
            - "8700:8700"
        sysctls:
            - net.core.somaxconn=65535
        depends_on:
            - mysql 

    nginx:
      image: nginx:1.19.5-alpine
      depends_on:
        - django
      ports:
        - "80:80" 
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
        - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
      restart: always